version: "3.8"

x-worker: &worker
  build: .
  stdin_open: true
  tty: true
  volumes:
    - .:/app
    - ./bundle:/usr/local/bundle
  depends_on:
    rabbitmq:
      condition: service_healthy
  environment:
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

services:
  rabbitmq:
    image: "rabbitmq:3.9.13-management-alpine"
    hostname: rabbit1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
      # environment:
      #   - RABBITMQ_NODENAME=rabbit@rabbit1
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 3s
      retries: 10

  demo_worker:
    <<: *worker
    command: bundle exec ruby ./run.rb DemoWorker

  logging_worker:
    <<: *worker
    command: bundle exec ruby ./run.rb LoggingWorker
