version: "3.8"
services:
  rabbitmq:
    image: "rabbitmq:3.9.13-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build: .
    volumes:
      - .:/app
      - ./bundle:/usr/local/bundle
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: ["bundle", "exec", "ruby", "./setup.rb"]
